### ISSUE TITLE
The number of constructor arguments in the derived class Controller must be >= than the number of constructor arguments of its base class

### ISSUE THREAD

**Issue by rafa-thayto** [expressots/expressots#28]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I create a controller without any useCases:
```ts
import { BaseController } from '@expressots/core'
import { controller, httpGet, response } from 'inversify-express-utils'

@controller('/health')
class HealthController extends BaseController {
  constructor() {
    super('health-controller')
  }

  @httpGet('/')
  execute(@response() res: any) {
    return res.send('alive')
  }
}

export { HealthController }
```
I've this error below:
```sh
[INFO] 21:49:15 Restarting: /home/thayto/projects/expresso/expressots-realworld-app/src/application/controllers/health.controller.ts has been modified
[2023-04-19 21:49:16] [core-api] [service-unknown] error: unhandledRejection: The number of constructor arguments in the derived class HealthController must be >= than the number of constructor arguments of its base class.
Error: The number of constructor arguments in the derived class HealthController must be >= than the number of constructor arguments of its base class.
    at /home/thayto/projects/expresso/expressots-realworld-app/node_modules/.pnpm/inversify@6.0.1/node_modules/inversify/src/planning/planner.ts:189:17
    at Array.forEach (<anonymous>)
    at _createSubRequests (/home/thayto/projects/expresso/expressots-realworld-app/node_modules/.pnpm/inversify@6.0.1/node_modules/inversify/src/planning/planner.ts:164:18)
    at plan (/home/thayto/projects/expresso/expressots-realworld-app/node_modules/.pnpm/inversify@6.0.1/node_modules/inversify/src/planning/planner.ts:240:5)
    at /home/thayto/projects/expresso/expressots-realworld-app/node_modules/.pnpm/inversify@6.0.1/node_modules/inversify/src/container/container.ts:623:25
    at Container._get (/home/thayto/projects/expresso/expressots-realworld-app/node_modules/.pnpm/inversify@6.0.1/node_modules/inversify/src/container/container.ts:574:37)
    at Container._getButThrowIfAsync (/home/thayto/projects/expresso/expressots-realworld-app/node_modules/.pnpm/inversify@6.0.1/node_modules/inversify/src/container/container.ts:580:25)
    at Container.getAll (/home/thayto/projects/expresso/expressots-realworld-app/node_modules/.pnpm/inversify@6.0.1/node_modules/inversify/src/container/container.ts:363:17)
    at getControllersFromContainer (/home/thayto/projects/expresso/expressots-realworld-app/node_modules/.pnpm/inversify-express-utils@6.4.3/node_modules/inversify-express-utils/src/utils.ts:16:26)
    at InversifyExpressServer.registerControllers (/home/thayto/projects/expresso/expressots-realworld-app/node_modules/.pnpm/inversify-express-utils@6.4.3/node_modules/inversify-express-utils/src/server.ts:149:56)
```

### Steps to reproduce

1. Create a crontroller withour any useCase on constructor
```ts
import { BaseController } from '@expressots/core'
import { controller, httpGet, response } from 'inversify-express-utils'

@controller('/health')
class HealthController extends BaseController {
  constructor() {
    super('health-controller')
  }

  @httpGet('/')
  execute(@response() res: any) {
    return res.send('alive')
  }
}

export { HealthController }
```

### Expected behavior

Don't break the code and runs the app as usual

### Package version

1.2.0

### Node.js version

18.15.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

Package Manager: PNPM
IDE: Neovim

**Comment by rafa-thayto** [comment]
The solution what I found is add any useCase inside the constructor:
```ts
import { AppUseCase } from '@application/use-cases/app.usecase'
import { BaseController } from '@expressots/core'
import { controller, httpGet, response } from 'inversify-express-utils'

@controller('/health')
class HealthController extends BaseController {
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  constructor(private _: AppUseCase) {
    super('health-controller')
  }

  @httpGet('/')
  execute(@response() res: any) {
    return res.send('alive')
  }
}

export { HealthController }
```
But I guess it still an issue

**Comment by rsaz** [comment]
Hi @rafa-thayto , if you update your library to `v1.3.0` this issue should be resolved, thank you!
```bash
npm i @expressots/core
```
[NPM Package v1.3.0](https://www.npmjs.com/package/@expressots/core?activeTab=readme)

If you still want to use your current library version, you can eliminate the inheritance from BaseController and your controller will act as any other endpoint with no issue. Before the change we have made on v1.3.0 the BaseController was requiring to have an use case injected. We understood that forcing the user passing a use case will match our opinionated idea but in the other hand removes the user flexibility of not having an use case if he/she don't want it too. And this is very common pattern in case the user want's to implement all controllers in one single file as MVC pattern does.

```typescript
@controller('/health')
class HealthController {

  @httpGet('/')
  execute(@response() res: any) {
    return res.send('alive')
  }
}
```
